services:
  gitlab:
    image: gitlab/gitlab-ce:17.3.6-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.redoctober.icu'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.redoctober.icu'
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - '/config:/etc/gitlab'
      - '/logs:/var/log/gitlab'
      - '/data:/var/opt/gitlab'
    shm_size: '256m'
